SET IDENTITY_INSERT [dbo].[Images] ON
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (2, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'nature', N'field trees clouds summer big tree', 3, N'поле деревья облака лето большое дерево', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (3, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'girl colorful coat autumn portrait', 4, N'девушка разноцветный пальто осенний портрет', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (4, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'girl with pink hair headphones profile portrait', 9, N'девушка с розовыми волосами наушники профиль портрет ', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (5, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'nature', N'nature blooming apple tree plant spring clouds white', 11, N'природа цветущая яблоня дерево растение весна облака белый', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (6, NULL, N'girls', N'beautiful blonde girl in a field of red poppies poppies greens summer village', 10, N'красивая девушка блондинка в поле красные маки мак зелень лето село', N'', N'2018-05-05 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (7, NULL, N'girls', N'beautiful girl brown-haired woman in white in the garden among roses pink rose nature', 10, N'красивая девушка русая шатенка в белом в саду среди роз розовые роза природа ', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (8, NULL, N'girls', N'beautiful girl dark-haired brown-haired brown eyes in golden city portrait', 4, N'красивая девушка темноволосая шатенка карие глаза в золотом город портрет', N'', N'2017-10-10 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (9, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'beautiful girl blonde blonde green-eyed green eyes in the village fence forest with flowers embroidered in the shirt', 3, N'красивая девушка светловолосая блондинка зеленоглазая зеленые глаза в деревне забор лес с цветами вышиванка в сорочке', N'', N'2012-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (10, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'beautiful girl brown-haired dark-haired black and white photo photograph portrait with hat lady', 3, N'красивая девушка шатенка темноволосая черно-белый снимок фотография портрет со шляпой дама', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (11, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'beautiful blonde blonde blonde blonde-haired green eyes in a room on a bed white gold beige', 4, N'красивая девушка блондинка русая светловолосая зеленые глаза в комнате на кровати белый золотой бежевый', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (12, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'nature', N'nature landscape mountains field dandelions dandelion forest clouds blue green spring summer', 9, N'природа пейзаж горы поле одуванчики одуванчик лес облака синий зеленый весна лето', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (13, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'girls', N'red-haired fox girl red-haired eyes portrait photo lake water body nature water', 11, N'рыжеволосая лиса девушка рыжая карие глаза портрет фото озеро река водоем природа вода ', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (14, NULL, N'animals', N'animals wolf thick furry standing wild dog autumn on the hunt', 10, N'животные волк толстый пушистый стоит дикая собака осень на охоте', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (15, NULL, N'girls', N'girl gorgeous redhead red-haired portrait hunter natural beauty white skin autumn on nature medieval girl', 10, N'девушка роскошная рыжая рыжеволосая портрет охотница естественная красота белая кожа осень на природе средневековая девушка ', N'', N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (16, NULL, N'girls', N'girl luxurious blonde blonde in red autumn on a nature background tree bushes yellow leaves green-eyed charming', 4, N'девушка роскошная блондинка светловолосая в красном осень на фоне природы дерево кусты желтые листья зеленоглазая очаровательная', N'', N'2017-10-10 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (17, NULL, N'nature', N'field trees clouds summer big tree', 3, N'поле деревья облака лето большое дерево', NULL, N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (18, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'animals', N'nature animals raccoon stretches up baby paws cubs raccoon grass greens', 3, N'природа животные енот тянется вверх малыш лапки детеныш енота трава зелень', NULL, N'2012-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (19, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'nature', N'nature landscape photo poppy field sunset clouds yellow sky red flowers summer village', 3, N'природа пейзаж фото маковое поле закат облака желтое небо красный цветы лето село', NULL, N'2012-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (20, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'nature', N'nature photo elephant elephants play hugging gray wild animals', 3, N'природа фото слон слоны играют обнимаются серые дикие животные', NULL, N'2014-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (21, NULL, N'girls', N'girl', 2, NULL, NULL, N'2018-04-20 00:00:00')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (24, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder
', 4.6, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:30:56')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (25, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder
', 4.6, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:30:56')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (26, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder
', 4.6, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:33:23')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (27, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder
', 4.6, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:33:23')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (28, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'
yellow tractor combine harvester repair digs earth transport running worker builder', 0, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель
', NULL, N'2018-05-10 14:38:27')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (29, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'
yellow tractor combine harvester repair digs earth transport running worker builder', 0, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель
', NULL, N'2018-05-10 14:38:27')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (30, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder', 0, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:42:13')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (31, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'yellow tractor combine harvester repair digs earth transport running worker builder', 0, N'желтый трактор комбайн ремонт копает землю транспорт работает работник строитель', NULL, N'2018-05-10 14:42:13')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (32, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'as', N'fgsd', 0, N'SDFGSDFG', NULL, N'2018-05-10 14:44:11')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (33, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'fgsd', 0, N'SDFGSDFG', NULL, N'2018-05-10 14:45:38')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (34, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'as', N'dfgs', 0, N'sdfgs', NULL, N'2018-05-10 14:46:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (35, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'as', N'dfgs', 0, N'sdfgs', NULL, N'2018-05-10 14:50:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (36, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'as', N'ddd', 5, N'ddd', NULL, N'2018-05-10 14:52:38')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (38, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'tractor transport yellow car construction work builders repair dig earth earth nature machinery', 4.32, N'трактор транспорт желтый машина строительные работы строители ремонт копать землю рыть землю природа техника', NULL, N'2018-05-14 12:48:33')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (39, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'transport', N'tractor transport yellow car construction work builders repair dig earth earth nature machinery', 4.32, N'трактор транспорт желтый машина строительные работы строители ремонт копать землю рыть землю природа техника', NULL, N'2018-05-14 12:48:33')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (40, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'cars', N'
yellow car sporty in the city asphalt dark background black stripes tuning', 3.32, N'желтая машина спортивная в городе асфальт темный фон черные полоски тюнинг', NULL, N'2018-05-14 13:19:53')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (42, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (43, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (44, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (45, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (46, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (47, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (48, N'cbdbd8dc-eeab-43f3-89a9-123a8c525c5b', N'handicraft', N'blower glass business master glassblower magic glass craftsman souvenir handicraft hands fire furnace', 3.76, N'стеклодув 
стекляных дел мастер стеклодув магия из стекла умелец сувенир ремесленик руки огонь печи ', NULL, N'2018-05-14 13:32:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (49, N'51ca936d-f091-4a0f-a77b-dc637fb6d404', N'guys', N' guy young man in suit in white shirt handsome stands sits', 2.32, N'парень молодой человек в костюме в белой рубашке красивый стоит сидит ', NULL, N'2018-05-14 17:13:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (50, N'51ca936d-f091-4a0f-a77b-dc637fb6d404', N'guys', N' guy young man in suit in white shirt handsome stands sits', 2, N'парень молодой человек в костюме в белой рубашке красивый стоит сидит ', NULL, N'2018-05-14 17:13:29')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (53, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:40:53')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (54, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (55, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (56, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (57, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (58, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (59, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (60, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (61, N'fcf86f7e-34f6-44f2-a627-3821a08606b4', N'scarlet sails', N'scarlet sails holiday graduates 2017 edition show st. petersburg extravaganza show firework ship sailer scarlet red sail', 2.3, N'алые паруса праздник выпускников 2017 выпуск шоу Санкт-Петербург феерия шоу феерверк корабль парусник алый красный парус', NULL, N'2018-05-15 14:41:41')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (64, N'51ca936d-f091-4a0f-a77b-dc637fb6d404', N'guys', N'guy in a jacket handsome young man blue suit pants white shirt portrait green spring spring', 2.32, N'парень в пиджаке красивый молодой человек голубой костюм  брюки белая рубашка портрет зелень весна лето', NULL, N'2018-05-15 16:54:18')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (65, N'51ca936d-f091-4a0f-a77b-dc637fb6d404', N'guys', N'guy in a jacket handsome young man blue suit pants white shirt portrait green spring spring', 0, N'парень в рубашке красивый молодой человек голубой костюм  брюки белая рубашка портрет зелень весна лето', NULL, N'2018-05-15 16:57:34')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (66, N'51ca936d-f091-4a0f-a77b-dc637fb6d404', N'guys', N'guy in jacket handsome young man blue suit pants white shirt portrait gray black background', 3.5, N'парень в пиджаке красивый молодой человек голубой костюм  брюки белая рубашка портрет серый черный фон', NULL, N'2018-05-15 16:58:24')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (67, N'19e44fd8-c362-48de-b6aa-33802afaf7c3', N'dogs, golden retriever', N'dogs', 5, N'dogs', NULL, N'2018-05-16 13:36:26')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (68, N'5b5b05cb-df2b-4b5d-881e-fd8d05cac359', N'animals', N'raccoon panda red panda small panda animal mammal predator summer grass greens orange reddish brown muzzle cute', 3.38, N'енотовидная панда красная панда малая панда животное млекопитающее хищник лето трава зелень оранжевый рыжий коричневый мордочка милый', NULL, N'2018-05-16 14:26:03')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (69, N'5b5b05cb-df2b-4b5d-881e-fd8d05cac359', N'animals', N'raccoon panda red panda small panda animal mammal predator summer grass greens orange reddish brown muzzle cute', 3.38, N'енотовидная панда красная панда малая панда животное млекопитающее хищник лето трава зелень оранжевый рыжий коричневый мордочка милый', NULL, N'2018-05-16 14:26:03')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (70, N'5b5b05cb-df2b-4b5d-881e-fd8d05cac359', N'animals', N'raccoon panda red panda small panda animal mammal predator summer grass greens orange reddish brown muzzle cute', 3.38, N'енотовидная панда красная панда малая панда животное млекопитающее хищник лето трава зелень оранжевый рыжий коричневый мордочка милый', NULL, N'2018-05-16 14:26:03')
INSERT INTO [dbo].[Images] ([ImageId], [ApplicationUserId], [Category], [KeyWords], [Price], [Description], [Url], [Date]) VALUES (71, N'5b5b05cb-df2b-4b5d-881e-fd8d05cac359', N'animals', N'raccoon panda red panda small panda animal mammal predator summer grass greens orange reddish brown muzzle cute', 3.38, N'енотовидная панда красная панда малая панда животное млекопитающее хищник лето трава зелень оранжевый рыжий коричневый мордочка милый', NULL, N'2018-05-16 14:26:03')
SET IDENTITY_INSERT [dbo].[Images] OFF
